name: native_toolchain_rust_mirror
description: Library to interact with rustup and cargo when building Dart and Flutter native assets written in Rust.  Mirrored by sneurlax from irondash for downstream package-publishing purposes until irondash incorporates library names; use the versions from irondash in production. This crate will be unpublished/deleted as soon as possible.
version: 0.1.0-dev.8
homepage: https://github.com/ManyMath/native_toolchain_rust_mirror.git

environment:
  sdk: ">=3.4.0-190.0.dev <4.0.0"

dependencies:
  native_toolchain_rust_common: ^0.1.0-dev.3
  collection: ^1.18.0
  logging: ^1.2.0
  native_assets_cli: ^0.7.2
  path: ^1.9.0
  process: ^5.0.2
  pub_semver: ^2.1.4
  toml: ^0.15.0
  rustup: ^0.1.0-dev.6

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0

